package com.tailtown.backend.platform.exception

enum class ErrorCode {
    VALIDATION_ERROR, UNAUTHORIZED, FORBIDDEN, NOT_FOUND,
    SLOT_UNAVAILABLE, OUT_OF_STOCK, BOOKING_CONFLICT, VERSION_CONFLICT,
    IDEMPOTENCY_CONFLICT, OTP_EXPIRED, OTP_INVALID, OTP_MAX_ATTEMPTS,
    REFRESH_TOKEN_INVALID, REFRESH_TOKEN_EXPIRED, RATE_LIMITED,
    PAYMENT_DECLINED, PAYMENT_ALREADY_CAPTURED, SUBSCRIPTION_ALREADY_ACTIVE,
    EMAIL_ALREADY_REGISTERED, PHONE_ALREADY_USED, MICROCHIP_ALREADY_EXISTS,
    CART_EMPTY, ADDRESS_IN_USE, PET_HAS_ACTIVE_BOOKINGS, CONVERSATION_CLOSED,
    REFERRAL_ALREADY_CLAIMED, SELF_REFERRAL_NOT_ALLOWED, INVALID_REFERRAL_CODE,
    SUBSCRIPTION_ALREADY_EXISTS, SKIP_WINDOW_CLOSED, CANCELLATION_WINDOW_CLOSED,
    WEIGHT_RECORD_DUPLICATE,
    INTERNAL_ERROR, EXTERNAL_SERVICE_ERROR;

    fun httpStatus(): Int = when (this) {
        VALIDATION_ERROR, OTP_EXPIRED, OTP_INVALID, OTP_MAX_ATTEMPTS,
        REFRESH_TOKEN_INVALID, CART_EMPTY -> 400
        UNAUTHORIZED, REFRESH_TOKEN_EXPIRED -> 401
        FORBIDDEN -> 403
        NOT_FOUND -> 404
        SLOT_UNAVAILABLE, OUT_OF_STOCK, BOOKING_CONFLICT, VERSION_CONFLICT,
        IDEMPOTENCY_CONFLICT, EMAIL_ALREADY_REGISTERED, PHONE_ALREADY_USED,
        MICROCHIP_ALREADY_EXISTS, REFERRAL_ALREADY_CLAIMED, SUBSCRIPTION_ALREADY_EXISTS,
        WEIGHT_RECORD_DUPLICATE, PAYMENT_DECLINED, PAYMENT_ALREADY_CAPTURED -> 409
        RATE_LIMITED -> 429
        INTERNAL_ERROR, EXTERNAL_SERVICE_ERROR -> 500
        else -> 422
    }
}
